version: "3.8"

services:
  backend:
    build: backend/
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      PORT: 4040

    container_name: backend

  frontend:
    build: frontend/
    restart: unless-stopped
    environment:
      REACT_APP_BASE_API_URL: http://localhost:4040
    ports:
      - 3000:3000
    links:
      - backend