env:
  es2021: true
  node: true
  mocha: true
extends:
  - google
parser: '@typescript-eslint/parser'
ignorePatterns:
  - dist/**
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  new-cap: off
  require-jsdoc: off
